### ISSUE TITLE
Getting Started Questions

### ISSUE THREAD

**Issue by dancancro** [CleverStack/angular-seed#78]
Here are a few things that I've come across while getting started:

1) First, could you explain a little about the subgenerators?  You've indicated [here](https://docs.google.com/spreadsheets/d/1r8rJy2Q5p5QORYKcye93UECwOlSgFL24c5fyF7dqhaM/edit#gid=1607194899) that Cleverstack offers subgenerators for config, controller, crud-mock, directive, factory, filter, model, provider, service, test and a few others, but I can't see how to run them or what the complete set of them is.
2) How do you specify options for the main application generator?   When I ran "clever init my-app", I wasn't asked any questions.  It would also be nice to be able to feed clever a json file with the answers and everything about my app and have it use that info to make the app for me.
3) How do you use the data migration/evolution system with Cleverstack?
4) How do you define a complex schema with objects that have properties that are objects that have primitive properties?
5) Is the intention to let you create one MyThingModel.js file that works with both relational and document databases?  What does it take to switch between using a document and a relational database?
6) After I log out of my app, the Logout button is still there.  Then if I refresh the page, I get the expected Login and Register buttons.
7) After I log in to my app, I see the Logout button and Users button. There are two user records in my Users table.  I click the Users button and see an empty users list with the message "There are currently no registered Users", and the following message in the browser console: 

    GET http://localhost:8080/user 401 (Unauthorized) 

8) After I log in to my app, I change the url to http://localhost:9000/mymodule.  My new module's page appears but instead of the logout button, I see the login and register buttons and get the console messages: 

    CSSessionProvider: using default loginStart method cs_session_provider.js:144
    CSSessionProvider: using default loginSuccess method cs_session_provider.js:148
    CSSessionProvider: using default locationChange method cs_session_provider.js:152
    CSSessionProvider: Welcome newcomer! cs_session_provider.js:231
    CSSessionProvider: Checking your session... cs_session_provider.js:232
    GET http://localhost:8080/user/current 404 (Not Found) angular.js:7962
    CSSessionProvider: request failed cs_session_provider.js:240
    CSSessionProvider: proceeding as guest. cs_session_provider.js:241
    CSSessionProvider: Guest access to /mymodule cs_session_provider.js:214
    CSSessionProvider: /mymodule is public 

9) The link on [this page](http://cleverstack.io/documentation/) to submit a new issue on [this page](https://github.com/CleverStack/cleverstack/issues) is broken.  Since cleverstack is multiple repositories, I guess you'll need links for submitting issues with each one.  While you're there, you might want to tweak the instructions so it's clear people are supposed to use github Issues for questions and discussions.  At the moment it says "bugs"

Thanks!
Dan

**Comment by pilsy** [comment]
Hi @dancancro, allot has changed since you opened this issue - you might have to rephrase some questions? otherwise i can just answer?

**Comment by dancancro** [comment]
Hi @pilsy, you have been busy.

I haven't looked at Cleverstack in a while.  So without knowing what's changed exactly, it's tough for me to know how to rephrase the questions.  Could you take a whack at answering them as is?  If something is no longer valid or you can't reproduce a misbehavior, just say so.

I see that #9 is still there.  The link at the very bottom of the page should be https://github.com/CleverStack/cleverstack-cli/issues/new instead of https://github.com/CleverStack/cleverstack/issues

**Comment by pilsy** [comment]
1) `clever generate -h`
2) This feature is being implemented in https://github.com/CleverStack/cleverstack-cli/issues/59
3) For information about Seed Data and using the Toolbelt, please see http://cleverstack.io/documentation/backend/models/#seed-data and http://cleverstack.io/documentation/backend/models/#toolbelt
4) For information about Assocations (etc) please see http://cleverstack.io/documentation/backend/models/#associations
5) All it takes is to change `type: 'ORM'` to `type: 'ODM'` inside the models definition, take a look at http://cleverstack.io/documentation/backend/models/#options for more information and at https://github.com/CleverStack/clever-users/blob/master/models/UserModel.js#L4 for an example of how i move that logic/option/choice out into the config files
6) This should no longer be an issue with the angular-seed
7) This should no longer be an issue
