### ISSUE TITLE
Missing JS and CSS files (index.html gets served instead)

### ISSUE THREAD

**Issue by mik01aj** [CleverStack/angular-seed#82]
`clever serve` responds with HTML to requests for JS and CSS files. Looks like something is missing.

![screenshot 2015-01-13 17 31 04](https://cloud.githubusercontent.com/assets/3027415/5724157/03a30100-9b4a-11e4-9585-5b0dda9d72c1.png)

This is right after initialization, I didn't change any configs yet.

**Comment by pilsy** [comment]
This happens when your bower components are not installed, try running `bower cache clean` then `clever setup`

**Comment by pilsy** [comment]
@mik01aj - did the above solution work for you?

**Comment by mik01aj** [comment]
I just checked it out and no, it doesn't change anything. Btw, I decided to use other libraries for my app, so I can no longer support you in this issue.

**Comment by pilsy** [comment]
The issue should be resolved now, with the latest commit https://github.com/CleverStack/angular-seed/commit/ca5cdaa5ca7739e051ca79d337146595d19c667b
