### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by lakakenny** [CleverStack/angular-seed#86]
I just try to use CleverStack but when i try http://localhost:9000/

Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:9000/components/fontawesome/css/font-awesome.css".
localhost/:19 Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:9000/components/angular-ui/build/angular-ui.css".
localhost/:20 Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:9000/components/ng-table/ng-table.min.css".
localhost/:22 Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:9000/components/jquery-minicolors/jquery.minicolors.css".
localhost/:23 Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:9000/components/select2/select2.css".
localhost/:24 Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:9000/components/select2/select2-bootstrap.css".
pace.min.js:1 Uncaught SyntaxError: Unexpected token <
localhost/:28 Resource interpreted as Script but transferred with MIME type text/html: "http://localhost:9000/components/pace/pace.min.js".
localhost/:50 Resource interpreted as Script but transferred with MIME type text/html: "http://localhost:9000/components/requirejs/require.js".
require.js:1 Uncaught SyntaxError: Unexpected token <
(index):72 GET http://localhost:35729/livereload.js?snipver=1 net::ERR_CONNECTION_REFUSED(anonymous function) @ (index):72

**Comment by pilsy** [comment]
Hi @lakakenny,

This usually happens when bower dependencies are not installed, if you take a look at the response for those HTTP Requests it will be the index.html file...

To fix it you can run `clever setup`, i would recommend running `bower cache clean` first and also if you run into issues with the clever setup command you should run `clever setup -v` to see verbose debugging output.
