### ISSUE TITLE
Error on clever initialization

### ISSUE THREAD

**Issue by marco-mazzocchi** [CleverStack/angular-seed#89]
Hi!
I'm trying to install clever locally but I encounter and error when the CLI try to install angular-seed.
In the npm-debug.log I've got these lines:

0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/Users/Alfred/.nvm/v0.10.38/bin/npm',
1 verbose cli   'run-script',
1 verbose cli   'setup-protractor' ]
2 info using npm@2.11.2
3 info using node@v0.10.38
4 verbose run-script [ 'presetup-protractor',
4 verbose run-script   'setup-protractor',
4 verbose run-script   'postsetup-protractor' ]
5 info presetup-protractor angular-seed@1.2.0-rc-2
6 info setup-protractor angular-seed@1.2.0-rc-2
7 verbose unsafe-perm in lifecycle true
8 info angular-seed@1.2.0-rc-2 Failed to exec setup-protractor script
9 verbose stack Error: angular-seed@1.2.0-rc-2 setup-protractor: `grunt webdriver:update`
9 verbose stack Exit status 3
9 verbose stack     at EventEmitter.<anonymous> (/Users/Alfred/.nvm/v0.10.38/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:98:17)
9 verbose stack     at ChildProcess.<anonymous> (/Users/Alfred/.nvm/v0.10.38/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:98:17)
9 verbose stack     at maybeClose (child_process.js:766:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
10 verbose pkgid angular-seed@1.2.0-rc-2
11 verbose cwd /Users/Alfred/Sites/clever-pillar/frontend
12 error Darwin 14.3.0
13 error argv "node" "/Users/Alfred/.nvm/v0.10.38/bin/npm" "run-script" "setup-protractor"
14 error node v0.10.38
15 error npm  v2.11.2
16 error code ELIFECYCLE
17 error angular-seed@1.2.0-rc-2 setup-protractor: `grunt webdriver:update`
17 error Exit status 3
18 error Failed at the angular-seed@1.2.0-rc-2 setup-protractor script 'grunt webdriver:update'.
18 error This is most likely a problem with the angular-seed package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     grunt webdriver:update
18 error You can get their info via:
18 error     npm owner ls angular-seed
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

Any idea? Do you any other information?
Thanks

**Comment by phamlehoaian** [comment]
Hello! I have same problem as this. Please help!

**Comment by pilsy** [comment]
Try this https://github.com/CleverStack/cleverstack-cli/issues/76#issuecomment-121777570

**Comment by marco-mazzocchi** [comment]
Hi! That works for  me, thank you very much!
