### ISSUE TITLE
Can't create an app

### ISSUE THREAD

**Issue by vurso** [CleverStack/angular-seed#94]
Hi,

Tried followed the simple instructions made sure all the pre-req's were installed however when I run the command:

clever init my-app

I get the following error about 75% of the way through:

`Error: Command failed: npm run-script setup-protractor

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86
in\npm-cli.js" "run-script" "setup-protractor"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@1.2.0-rc-2 setup-protractor: `grunt webdriver:update`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the angular-seed@1.2.0-rc-2 setup-protractor script 'grunt web
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt webdriver:update
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Tools\Console2\my-app\frontend\npm-debug.log

Error: Command failed: npm run-script setup-protractor

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86
in\npm-cli.js" "run-script" "setup-protractor"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@1.2.0-rc-2 setup-protractor: `grunt webdriver:update`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the angular-seed@1.2.0-rc-2 setup-protractor script 'grunt web
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt webdriver:update
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Tools\Console2\my-app\frontend\npm-debug.log

```
at ChildProcess.exithandler (child_process.js:202:12)
at emitTwo (events.js:100:13)
at ChildProcess.emit (events.js:185:7)
at maybeClose (internal/child_process.js:850:16)
at Socket.<anonymous> (internal/child_process.js:323:11)
at emitOne (events.js:90:13)
at Socket.emit (events.js:182:7)
at Pipe._onclose (net.js:479:12)
```

From previous event:
    at C:\Users\Tahir\AppData\Roaming\npm\node_modules\cleverstack-cli\bin\clever
    at processImmediate [as _immediateCallback](timers.js:516:17)
From previous event:
    at C:\Users\Tahir\AppData\Roaming\npm\node_modules\cleverstack-cli\bin\clever
    at C:\Users\Tahir\AppData\Roaming\npm\node_modules\cleverstack-cli\node_modul
    at FSReqWrap.oncomplete (fs.js:82:15)
Status @ 4.567m |   Installation Progress: [▒▒▒▒▒▒▒▒--]  79 %   ┊   Installing: F
protractor (this might take awhile)...   ┊   Step Time: 2s   ┊`

Environment spec is:

Windows 8.1 Professional
i7 Quad Core / 32GB Ram / SSD

node.js (latest version) installed correctly and working.  Yeoman worked btw even though it complained about python etc.

Thanks,

T

**Comment by pilsy** [comment]
Look's like there was an issue with the setup-protractor script, the app was still created and will work -- it's just the protractor tests wouldn't run -- you can skip the installation of protractor by using the `-S` or `--skip-protractor` command line argument.

This error creep's up on some OS/Node/NPM version combo's and i sadly don't have enough time to track down and fix every single combo, vagrant, docker or any virtual machine is the easiest way for you to get everything working perfect on your particular combo (that is if you don't have the time or knowledge to debug your combo)

For reference to anyone reading this, if you have this problem -- post in any of the gitter chat rooms for the CleverStack repo's and we can work through your issue

**Comment by vurso** [comment]
Thanks will give it another go.
